name: Django Deployment to EC2

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/ticket-barter
            git pull origin production
            cd /home/ubuntu/ticket-barter/django-app
            python3 -m pip install -r requirements.txt
            pkill gunicorn
            gunicorn trade_barter.wsgi:application --bind 0.0.0.0:3000 --preload --daemon
